import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import React from "react";
import ProgressWrapper from "@/components/common/progress.wrapper";
import ScrollToTop from "@/components/common/scroll.to.top";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f9f7f7]`}
        >
        <ProgressWrapper>
            <main className='select-none'>
                {children}
                <ScrollToTop/>
            </main>
        </ProgressWrapper>
        <Toaster
            position="top-center"
            toastOptions={{
                className: 'text-sm shadow-md rounded-lg text-amber-500 text-center',
            }}
        ></Toaster>
        </body>
        </html>
    );
}
